name: Send a Discord message when new RSS feeds update
on:
  rss:
    url: https://www.google.co.kr/alerts/feeds/09139258619343329046/13614290289565164400
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_US }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_US }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_US }}
        uses: Ilshidur/action-discord@master
        with:
          args: "'`'🇺🇸 Google 알리미 - Migraine'`''\n'**${{on.rss.outputs.title}}**'\n'${{on.rss.outputs.link}}"
